### ISSUE TITLE
Governance Call 3 not on Community Calendar

### ISSUE THREAD

**Issue by whoabuddy** [blockstackers/contribute-blockstack#4]
The [3rd governance call](https://github.com/stacksgov/pm/issues/5) is not on the [Blockstack community calendar](https://community.blockstack.org/events).

**Comment by lrettig** [comment]
Good catch. How do we add things to that calendar? 🤔

**Comment by whoabuddy** [comment]
I believe this is the best spot, will let you know if I am told otherwise. Per [Community Project & Communications Management](https://forum.blockstack.org/t/proposal-community-project-communications-management/10412) post on the forum.

**Comment by whoabuddy** [comment]
Link is live! (thanks Jenny!) https://community.blockstack.org/events#event=38117013
